//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzariaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PizzariaDoZe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _291125 {
            get {
                object obj = ResourceManager.GetObject("291125", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN_10_SAIR {
            get {
                return ResourceManager.GetString("BTN_10_SAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN_11_SAIR {
            get {
                return ResourceManager.GetString("BTN_11_SAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INGREDIENTES.
        /// </summary>
        internal static string BTN_7_INGREDIENTES_Text {
            get {
                return ResourceManager.GetString("BTN_7_INGREDIENTES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PRODUTOS.
        /// </summary>
        internal static string BTN_7_PRODUTOS_Text {
            get {
                return ResourceManager.GetString("BTN_7_PRODUTOS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SABORES.
        /// </summary>
        internal static string BTN_7_SABORES_Text {
            get {
                return ResourceManager.GetString("BTN_7_SABORES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VALORES.
        /// </summary>
        internal static string BTN_7_VALORES_Text {
            get {
                return ResourceManager.GetString("BTN_7_VALORES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN_8_SAIR_Text {
            get {
                return ResourceManager.GetString("BTN_8_SAIR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN_9_SAIR {
            get {
                return ResourceManager.GetString("BTN_9_SAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRAR.
        /// </summary>
        internal static string BTN_CADASTRAR_Text {
            get {
                return ResourceManager.GetString("BTN_CADASTRAR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ADMINISTRADOR.
        /// </summary>
        internal static string BTN_LOGIN_ADM_Text {
            get {
                return ResourceManager.GetString("BTN_LOGIN_ADM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PEDIDOS.
        /// </summary>
        internal static string BTN_PEDIDOS_Text {
            get {
                return ResourceManager.GetString("BTN_PEDIDOS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN_SAIR_Text {
            get {
                return ResourceManager.GetString("BTN_SAIR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SALVAR.
        /// </summary>
        internal static string BTN_SALVAR_INGREDIENTES_Text {
            get {
                return ResourceManager.GetString("BTN_SALVAR_INGREDIENTES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRAR.
        /// </summary>
        internal static string BTN1_CADASTRO_CLIENT_Text {
            get {
                return ResourceManager.GetString("BTN1_CADASTRO_CLIENT.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CLIENTE.
        /// </summary>
        internal static string BTN1_CLIENTES_Text {
            get {
                return ResourceManager.GetString("BTN1_CLIENTES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENTRAR.
        /// </summary>
        internal static string BTN1_LOGIN_Text {
            get {
                return ResourceManager.GetString("BTN1_LOGIN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN1_SAIR_Text {
            get {
                return ResourceManager.GetString("BTN1_SAIR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string Btn20_SAIR_Text {
            get {
                return ResourceManager.GetString("Btn20_SAIR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN4_VOLTAR {
            get {
                return ResourceManager.GetString("BTN4_VOLTAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENVIAR.
        /// </summary>
        internal static string BTN5_ENVIAR_Text {
            get {
                return ResourceManager.GetString("BTN5_ENVIAR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VOLTAR.
        /// </summary>
        internal static string BTN5_VOLTAR_Text {
            get {
                return ResourceManager.GetString("BTN5_VOLTAR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VOLTAR.
        /// </summary>
        internal static string BTN6_VOLTAR_Text {
            get {
                return ResourceManager.GetString("BTN6_VOLTAR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CLIENTES.
        /// </summary>
        internal static string BTN7_CLIENTES_Text {
            get {
                return ResourceManager.GetString("BTN7_CLIENTES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FUNCIONÁRIOS.
        /// </summary>
        internal static string BTN7_FUNCIONARIOS_Text {
            get {
                return ResourceManager.GetString("BTN7_FUNCIONARIOS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN7_SAIR_Text {
            get {
                return ResourceManager.GetString("BTN7_SAIR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FAZER PEDIDO.
        /// </summary>
        internal static string BTN8_FAZER_PEDIDO_Text {
            get {
                return ResourceManager.GetString("BTN8_FAZER_PEDIDO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VER PEDIDOS PENDENTES.
        /// </summary>
        internal static string BTN8_PENDENTES {
            get {
                return ResourceManager.GetString("BTN8_PENDENTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CATALOGO DE SABORES.
        /// </summary>
        internal static string BTN8_SABORES {
            get {
                return ResourceManager.GetString("BTN8_SABORES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SAIR.
        /// </summary>
        internal static string BTN8_SAIR {
            get {
                return ResourceManager.GetString("BTN8_SAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CATEGORIA.
        /// </summary>
        internal static string CATEGORIA_SABOR_Text {
            get {
                return ResourceManager.GetString("CATEGORIA_SABOR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_bullet_list_30 {
            get {
                object obj = ResourceManager.GetObject("icons8-bullet-list-30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_lock_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-lock-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_menu_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-menu-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_menu_squared_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-menu-squared-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_reminders_50 {
            get {
                object obj = ResourceManager.GetObject("icons8-reminders-50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_user_male_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-user-male-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string ING_NOME {
            get {
                return ResourceManager.GetString("ING_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1137028124_612x612 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1137028124-612x612", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRO ATENDENTE.
        /// </summary>
        internal static string LABEL1_Text {
            get {
                return ResourceManager.GetString("LABEL1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HABILITAÇÃO - A.
        /// </summary>
        internal static string RADIO6_HAB_A_Text {
            get {
                return ResourceManager.GetString("RADIO6_HAB_A.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HABILITAÇÃO - B.
        /// </summary>
        internal static string RADIO6_HAB_B_Text {
            get {
                return ResourceManager.GetString("RADIO6_HAB_B.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HABILITAÇÃO - C.
        /// </summary>
        internal static string RADIO6_HAB_C_Text {
            get {
                return ResourceManager.GetString("RADIO6_HAB_C.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HABILITAÇÃO - D.
        /// </summary>
        internal static string RADIO6_HAB_D_Text {
            get {
                return ResourceManager.GetString("RADIO6_HAB_D.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CÓDIGO.
        /// </summary>
        internal static string SABOR_COD_Text {
            get {
                return ResourceManager.GetString("SABOR_COD.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a FOTO.
        /// </summary>
        internal static string SABOR_FOTO_Text {
            get {
                return ResourceManager.GetString("SABOR_FOTO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INGREDIENTES.
        /// </summary>
        internal static string SABOR_INGREDIENTES_Text {
            get {
                return ResourceManager.GetString("SABOR_INGREDIENTES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string SABOR_NOME_Text {
            get {
                return ResourceManager.GetString("SABOR_NOME.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Screenshot_1 {
            get {
                object obj = ResourceManager.GetObject("Screenshot_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ML.
        /// </summary>
        internal static string TEXT_10_ML_Text {
            get {
                return ResourceManager.GetString("TEXT_10_ML.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string TEXT_10_NOME_Text {
            get {
                return ResourceManager.GetString("TEXT_10_NOME.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TIPO.
        /// </summary>
        internal static string TEXT_10_TIPO_Text {
            get {
                return ResourceManager.GetString("TEXT_10_TIPO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VALOR.
        /// </summary>
        internal static string TEXT_10_VALOR_Text {
            get {
                return ResourceManager.GetString("TEXT_10_VALOR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CATEGORIA.
        /// </summary>
        internal static string TEXT_9_CATEGORIAS_Text {
            get {
                return ResourceManager.GetString("TEXT_9_CATEGORIAS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TAMANHOS.
        /// </summary>
        internal static string TEXT_9_TAMANHOS_Text {
            get {
                return ResourceManager.GetString("TEXT_9_TAMANHOS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VALOR.
        /// </summary>
        internal static string TEXT_9_VALOR {
            get {
                return ResourceManager.GetString("TEXT_9_VALOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VALOR ADICIONAL BORDA.
        /// </summary>
        internal static string TEXT_9_VALORES_ADICIONAIS_Text {
            get {
                return ResourceManager.GetString("TEXT_9_VALORES_ADICIONAIS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENDEREÇO.
        /// </summary>
        internal static string TEXT_ENDERECO_Text {
            get {
                return ResourceManager.GetString("TEXT_ENDERECO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string TEXT_NOME_Text {
            get {
                return ResourceManager.GetString("TEXT_NOME.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PRIMEIRA VEZ? CRIE UMA CONTA!.
        /// </summary>
        internal static string TEXT_PRIMEI_VEZ_Text {
            get {
                return ResourceManager.GetString("TEXT_PRIMEI_VEZ.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a JÁ TEM UMA CONTA? FAÇA LOGIN.
        /// </summary>
        internal static string TEXT1_FACA_LOGIN_Text {
            get {
                return ResourceManager.GetString("TEXT1_FACA_LOGIN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a MENU.
        /// </summary>
        internal static string TEXT1_MENU_Text {
            get {
                return ResourceManager.GetString("TEXT1_MENU.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONFIRMAR SENHA.
        /// </summary>
        internal static string TEXT4_CNF_SENHA {
            get {
                return ResourceManager.GetString("TEXT4_CNF_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string TEXT4_CPF {
            get {
                return ResourceManager.GetString("TEXT4_CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EMAIL.
        /// </summary>
        internal static string TEXT4_EMAIL {
            get {
                return ResourceManager.GetString("TEXT4_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENDEREÇO.
        /// </summary>
        internal static string TEXT4_ENDERECO {
            get {
                return ResourceManager.GetString("TEXT4_ENDERECO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string TEXT4_NOME {
            get {
                return ResourceManager.GetString("TEXT4_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SENHA.
        /// </summary>
        internal static string TEXT4_SENHA {
            get {
                return ResourceManager.GetString("TEXT4_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TELEFONE.
        /// </summary>
        internal static string TEXT4_TELEFONE {
            get {
                return ResourceManager.GetString("TEXT4_TELEFONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONFIRMAR SENHA.
        /// </summary>
        internal static string TEXT5_CNF_SENHA_Text {
            get {
                return ResourceManager.GetString("TEXT5_CNF_SENHA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string TEXT5_CPF_Text {
            get {
                return ResourceManager.GetString("TEXT5_CPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EMAIL.
        /// </summary>
        internal static string TEXT5_EMAIL_Text {
            get {
                return ResourceManager.GetString("TEXT5_EMAIL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENDEREÇO.
        /// </summary>
        internal static string TEXT5_ENDERECO_Text {
            get {
                return ResourceManager.GetString("TEXT5_ENDERECO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string TEXT5_NOME_Text {
            get {
                return ResourceManager.GetString("TEXT5_NOME.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SENHA.
        /// </summary>
        internal static string TEXT5_SENHA_Text {
            get {
                return ResourceManager.GetString("TEXT5_SENHA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TELEFONE.
        /// </summary>
        internal static string TEXT5_TELEFONE_Text {
            get {
                return ResourceManager.GetString("TEXT5_TELEFONE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CONFIRMAR SENHA.
        /// </summary>
        internal static string TEXT6_CNF_SENHA_Text {
            get {
                return ResourceManager.GetString("TEXT6_CNF_SENHA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string TEXT6_CPF_Text {
            get {
                return ResourceManager.GetString("TEXT6_CPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EMAIL.
        /// </summary>
        internal static string TEXT6_EMAIL_Text {
            get {
                return ResourceManager.GetString("TEXT6_EMAIL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ENDEREÇO.
        /// </summary>
        internal static string TEXT6_ENDERECO_Text {
            get {
                return ResourceManager.GetString("TEXT6_ENDERECO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NOME.
        /// </summary>
        internal static string TEXT6_NOME_Text {
            get {
                return ResourceManager.GetString("TEXT6_NOME.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OBSERVAÇÃO:.
        /// </summary>
        internal static string TEXT6_OBSERVACAO_Text {
            get {
                return ResourceManager.GetString("TEXT6_OBSERVACAO.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECIONE A HABILITAÇÃO:.
        /// </summary>
        internal static string TEXT6_SEL_HAB_Text {
            get {
                return ResourceManager.GetString("TEXT6_SEL_HAB.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SENHA.
        /// </summary>
        internal static string TEXT6_SENHA_Text {
            get {
                return ResourceManager.GetString("TEXT6_SENHA.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TELEFONE.
        /// </summary>
        internal static string TEXT6_TELEFONE_Text {
            get {
                return ResourceManager.GetString("TEXT6_TELEFONE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ATA DO VENCIMENTO DA \r\nCARTEIRA DE MOTORISTA.
        /// </summary>
        internal static string TEXT6_VALID_HAB_Text {
            get {
                return ResourceManager.GetString("TEXT6_VALID_HAB.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TIPO.
        /// </summary>
        internal static string TIPO_SABOR_Text {
            get {
                return ResourceManager.GetString("TIPO_SABOR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRAR PRODUTOS.
        /// </summary>
        internal static string TIT_10_CADASTRAR_PRODUTOS_Text {
            get {
                return ResourceManager.GetString("TIT_10_CADASTRAR_PRODUTOS.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRO DE INGREDIENTES.
        /// </summary>
        internal static string TIT_11_INGREDIENTES_Text {
            get {
                return ResourceManager.GetString("TIT_11_INGREDIENTES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRO DE ADMINISTRADOR.
        /// </summary>
        internal static string TIT_ADM_Text {
            get {
                return ResourceManager.GetString("TIT_ADM.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        internal static string TIT_CPF_Text {
            get {
                return ResourceManager.GetString("TIT_CPF.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a EMAIL.
        /// </summary>
        internal static string TIT_EMAIL_Text {
            get {
                return ResourceManager.GetString("TIT_EMAIL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a TELEFONE.
        /// </summary>
        internal static string TIT_TELEFONE_Text {
            get {
                return ResourceManager.GetString("TIT_TELEFONE.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRAR VALORES.
        /// </summary>
        internal static string TIT12_CADASTRAR_Text {
            get {
                return ResourceManager.GetString("TIT12_CADASTRAR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRO DE ENTREGADOR.
        /// </summary>
        internal static string TIT6_ENTREGADOR_Text {
            get {
                return ResourceManager.GetString("TIT6_ENTREGADOR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRAR:.
        /// </summary>
        internal static string TIT7_CADASTRAR_Text {
            get {
                return ResourceManager.GetString("TIT7_CADASTRAR.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRO DE SABORES.
        /// </summary>
        internal static string TIT8_CADASTRO_SABORES_Text {
            get {
                return ResourceManager.GetString("TIT8_CADASTRO_SABORES.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CADASTRO DE CLIENTES.
        /// </summary>
        internal static string TITULO_CADASTRO_CLI_Text {
            get {
                return ResourceManager.GetString("TITULO_CADASTRO_CLI.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PIZZARIA DO ZÉ.
        /// </summary>
        internal static string TITULO_PRINCIPAL_Text {
            get {
                return ResourceManager.GetString("TITULO_PRINCIPAL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PIZZARIA DO ZÉ.
        /// </summary>
        internal static string Titulo8_Principal {
            get {
                return ResourceManager.GetString("Titulo8_Principal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a VOLTAR.
        /// </summary>
        internal static string VOLTAR_CAD_INGREDIENTES_Text {
            get {
                return ResourceManager.GetString("VOLTAR_CAD_INGREDIENTES.Text", resourceCulture);
            }
        }
    }
}
